### ISSUE TITLE
Build error when a third-party IntelliJ IDEA plugin depends on Dart (v502.0.0)

### ISSUE THREAD

**Issue by mdddj** [flutter/dart-intellij-third-party#223]
**Describe the bug**
I developed a Flutter IntelliJ IDEA plugin ([FlutterX](https://plugins.jetbrains.com/plugin/18986-flutterx?noRedirect=true)) that compiled successfully with Dart 500.0.0, but after upgrading the dependency to 502.0.0, a compilation error occurs.

**To Reproduce**
1.	Clone the repository: `https://github.com/mdddj/dd_flutter_idea_plugin`
2.	Switch to the `6.9.1` branch
3.	Run `./gradlew classes`

**Expected behavior**
The compilation was completed normally.

**Screenshots**

<img width="1574" height="532" alt="Image" src="https://github.com/user-attachments/assets/5f97bcf6-9294-4a69-9203-66e82e36af55" />

**Version information**
 - Dart plugin version: 502.0.0
 - IDE platform version: 2025.2.1
 - OS: Mac

**Error messages / Logs / Other context**
```kotlin
> Task :checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :convertXmlValueResourcesForMain NO-SOURCE
> Task :copyNonXmlValueResourcesForMain NO-SOURCE
> Task :prepareComposeResourcesTaskForMain NO-SOURCE
> Task :generateResourceAccessorsForMain SKIPPED
> Task :generateActualResourceCollectorsForMain SKIPPED
> Task :generateComposeResClass SKIPPED
> Task :generateFlutterPluginInfo UP-TO-DATE
> Task :assembleMainResources UP-TO-DATE
> Task :initializeIntellijPlatformPlugin
> Task :patchPluginXml
> Task :processResources UP-TO-DATE

> Task :compileKotlin FAILED
e: file:///Users/ldd/.gradle/caches/9.2.0/transforms/dfe303fd2ebea6631071a8e38dda53ce/transformed/Dart-502.0.0/Dart/lib/Dart-502.0.0.jar!/META-INF/Dart.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.3.0, expected version is 2.1.0.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

```
